name: Blob storage website CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - users/tiju/azure_pipelines

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install & build
        run: |
          # Build and test the project, then
          # deploy to Azure Web App.
          npm install
          npm run build
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name tournamentwebdev --auth-mode key -d '$web' -s ./build
      #- name: Purge CDN endpoint
      #  uses: azure/CLI@v1
      #  with:
      #    inlineScript: |
      #      az cdn endpoint purge --content-paths  "/*" --profile-name odw-cdn --name react-dev-cdn-endpoint --resource-group odw-frontend-dev
      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
